version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DB_HOST: mysql
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - nestjs-boilerplate

  mysql:
    image: mysql:8
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - nestjs-boilerplate

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links: 
      - mysql
    ports:
      - '8080:80'
    depends_on: 
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    networks:
      - nestjs-boilerplate

networks:
  nestjs-boilerplate: