# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'

  push:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.5
        options: '--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3'
        env:
          POSTGRES_USER: 'nestjs_test'
          POSTGRES_PASSWORD: 'nestjs_test'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Run NPM Install
        run: npm install

      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URL="postgres://nestjs_test:nestjs_test@localhost:5432/nestjs_test">> .env
          cat .env
      
      - name: Run Migration
        run: npx prisma migrate dev --name "init"

      - name: Run Testing
        run: npm run test:cov

      - name: Set Up Codeclimate and Send Report Codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
        with:
          coverageLocations: coverage/lcov.info:lcov
