# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: ci

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'

  push:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        options: '--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3'
        env:
          MYSQL_ROOT_PASSWORD: 'nestjs-boilerplate'
          MYSQL_USER: 'nestjs-boilerplate'
          MYSQL_PASSWORD: 'nestjs-boilerplate'
          MYSQL_DATABASE: 'nestjs-boilerplate'
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: '14'

      - name: Run NPM Install
        run: npm install

      - name: Create env file
        run: |
          touch .env
          echo DB_USERNAME="nestjs-boilerplate">> .env
          echo DB_PASSWORD="nestjs-boilerplate">> .env
          echo DB_DATABASE="nestjs-boilerplate">> .env
          cat .env

      - name: Run Testing
        run: npm run test:cov

      - name: Set Up Codeclimate and Send Report Codeclimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
        with:
          coverageLocations: coverage/lcov.info:lcov